## Stat340 Assignment 2

### Question 12
```{r}
middle_square = function(num,iteration=20) {
  base = 10000
  lst = c(num/base)
  for (i in 1:iteration) {
    sqr = paste("0000000",num^2,sep='')
    l = nchar(sqr)
    if (l>8)
      sqr = substr(sqr,l-7,l)
    num = as.integer(substr(sqr,3,6))
    lst = c(lst,num/base)
  }
  lst
}
middle_square(7182)
middle_square(1009)
```

Clearly, the algorithm is not quite good, as it converges to 0 quickly.

### Question 13
#### part a
```{r}
LCG = function(num,iteration=20){
  lst = c(num)
  for (i in 1:iteration){
    num = (5*num+3)%%16
    lst = c(lst,num)
  }
  lst
}
LCG(7)
```

#### part b
```{r}
MRG = function(past,curr,iteration=15){
  lst = c(curr)
  for (i in 2:iteration){
    temp = curr
    curr = (5*past+3*curr)%%100
    past = temp
    lst = c(lst,curr)
  }
  lst
}
MRG(23,66)
```

### Question 14
```{r,fig.height=4,fig.width=8}
RANDU = function(num,iteration=2000){
  lst = c()
  base = 2^31
  for (i in 1:iteration){
    num = ((2**16+3)*num)%%base
    lst = c(lst,num/base)
  }
  lst
}

result=RANDU(123456)
par(mfcol=c(1,2))
plot(result,pch=20)
qqnorm(result)
qqline(result)
```

The Q-Q plot shows quite heavy tails, thus the result is not truly random.

### Question 15
```{r,fig.height=2.5,fig.width=2.5}
PRNG = function(mass,output,population){
  findInterval(runif(population),cumsum(mass))+1
}
mass = c(1/6,1/3,1/2)
output = 1:3
rest = PRNG(mass,output,100000)
table(rest)
hist(rest,main="histogram of result")
```

